### ISSUE TITLE
Review 3: Updated BalanceSheetInput.jsx

### ISSUE THREAD

**Issue by skulibas** [ICS-414-In5PIRE/in5PIRE-code#113]
Please review the Balance Sheet Input, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/BalanceSheetInput.jsx)

Use these guidelines:
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

DUE: 9/30 11:30AM

**Comment by ehsuGit** [comment]
Architecture OK
Design OK
JS and ESLint -- 07 remove console log on line 57
React OK

**Comment by skulibas** [comment]
* Design-02: The render method has nested conditionals inside the Segment for rendering components based on the activeItem.
* Design-08: The error handling code is repeated in handleSubmit.

**Comment by bobbyir** [comment]
JS-07: Avoid console.log statements

There is a console.log in componentDidUpdate:

**Comment by daomcgill** [comment]
Design-01: An array could be defined for menu items, and then used in the rendering
JS-07: Remove console.log

**Comment by bfd2** [comment]
L57: Remove console.log (JS-07)
Rest is OK

**Comment by lukepag** [comment]
Design-08: error handling exists in handleSubmit and in rendering. Not sure if this is necessary

**Comment by Ssunoo2** [comment]
L07: Remove console.log

**Comment by Ssunoo2** [comment]
## Outcome of review Meeting

### New issues


### New checklist items
