### ISSUE TITLE
Review 3: Dashboard.jsx

### ISSUE THREAD

**Issue by skulibas** [ICS-414-In5PIRE/in5PIRE-code#114]
Please review the Dashboard, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/Dashboard.jsx)

Use these guidelines:
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

DUE: 9/30 11:30AM

**Comment by ehsuGit** [comment]
Architecture OK
Design -- 01 - Does look repeatitive, but not sure if there is a way to refactor in a way that would keep the years/data separated? if not this is good, organized and readable
JS and ESLint -- 08 - Could have a comment block at the top detailing what this file does 
React OK

**Comment by skulibas** [comment]
* Design-01: There are multiple sections in the chartConfigs for 4, 8, and 12 years that could be refactored into a single function to create chart configurations dynamically, reducing code duplication.
* Design-05: Some comments could be clearer. For instance, comments like "Use the real financial data" could be more descriptive regarding the expected structure of financialData.
* Design-08: The repeated definition of chart configurations for different years indicates a need for DRY principles. Consider creating a function to generate these configurations based on parameters.

**Comment by bobbyir** [comment]
REACT-01: Components should be simple.

Should have smaller components, each handling specific aspects of the dashboard ( separate components for each chart configuration).

**Comment by bfd2** [comment]
A block comment at the top of the main function would be helpful to explain what the function actually does.
Otherwise looks good and readable, could refactor to avoid redundancy (although this is better to keep track and debug)

**Comment by lukepag** [comment]
Design-01: Chart configurations do look redundant at first glance, but it's still very readable

**Comment by Ssunoo2** [comment]
Maybe adding more descriptive error handling for staticfinancials.find()

**Comment by Ssunoo2** [comment]
## Outcome of review Meeting

### New issues


### New checklist items
