### ISSUE TITLE
Review Issue: UploadFile.jsx

### ISSUE THREAD

**Issue by ehsuGit** [ICS-414-In5PIRE/in5PIRE-code#127]
Please review the UploadFile.jsx, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/UploadFile.jsx)

Use these guidelines:
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

DUE: 10/7

**Comment by Ssunoo2** [comment]
L15: could add function comments
Could add more descriptive error messages
Could add loading message
L26 specifies fourth sheet, not first

**Comment by skulibas** [comment]
- JS-04: line 22 could be destructored
- JS-08: Use JSDoc comment on line 14
- REACT-01: Maybe simplify the page by putting table rendering logic in its own functional component?

**Comment by daomcgill** [comment]
Design-04: In the comment: UploadFile, not UploadsFile. There could be more comments here.
Also, the comment says .csv files, but the code is reading .xlsx files. Either add support for .csv or change the comment at the top.
Line 27: First sheet would be at index 0.

**Comment by bobbyir** [comment]
Show a loading indicator while the files is being processed
File type validation should accepts csv files. (accepts only .xlsx, .xls, and .xlsm)

**Comment by bfd2** [comment]
- Re-edit comments to be correct
- Add block comment above handleFileUpload to explain what it does

**Comment by ehsuGit** [comment]
Architecture OK
Design 04 - Comment on line 7 should be changed to UploadFile.jsx
JS and ESLint 08 - Could have more comments detailing the function of the file. Could add a swal section to confirm file upload
React 01 - Could break up the code and have the file handling in a different file. Also doesn't look like it can handle files other than xlsx yet?

**Comment by lukepag** [comment]
Render statement seems like it could be simplified as a separate component
Other than that, just comments could be updated
