### ISSUE TITLE
Review Issue: BalanceSheetInputsCollection.js

### ISSUE THREAD

**Issue by ehsuGit** [ICS-414-In5PIRE/in5PIRE-code#128]
Please review the BalanceSheetInputsCollection.js, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/api/BalanceSheetInput/BalanceSheetInputsCollection.js)

Use these guidelines:
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

DUE: 10/7

**Comment by Ssunoo2** [comment]
Duplicated code: the list is duplicated many times. You can create a common list of the fields and then refer to them in your functions
Dry principles: define and dumpOne both have repeated fields

**Comment by bobbyir** [comment]
Files names should use camel case

**Comment by skulibas** [comment]
- Design-01: The define and dumpOne methods have similar patterns in terms of handling document properties.
- Design-05: the comment on define could be simplified
- Design-07: long lists of parameters in the define method

**Comment by daomcgill** [comment]
Refactor handling of the long list of parameters. It is used multiple times.

**Comment by bfd2** [comment]
- define and dumpOne have similar parameters
- Have a common list of fields for that long list of parameters.

**Comment by ehsuGit** [comment]
Architecture 02 - File name is BalanceSheetInputsCollection, folder is named BalanceSheetInput and other file is BalanceSheetInputSchema. Change file name to BalanceSheetInputCollection 
Design 01/08 - The huge blocks of input data could be stored somewhere else, duplicated 4 times in the code
09 - Duplicated code could be moved somewhere else for reuse
JS and ESLint -- 07 remove console log on line 57
React OK

**Comment by lukepag** [comment]
File name can be changed to keep consistency
Duplicate code that also seems a bit too long to use as a parameter
