### ISSUE TITLE
Review Issue 5: EditFinancialProfile.jsx

### ISSUE THREAD

**Issue by ehsuGit** [ICS-414-In5PIRE/in5PIRE-code#130]
Please review the EditFinancialProfile.jsx, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/EditFinancialProfile.jsx)

Use these guidelines:
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

DUE: 10/14

**Comment by skulibas** [comment]
* Design-03: The commented-out <MemberListDropdown members={members} /> (line 189) should either be removed if not needed or properly archived.
* JS-01: Variable names like fRef (line 166) should be more descriptive. 
* REACT-07: The line const profileData = FinancialProfiles.findOne(profileId); retrieves data directly in the reactive function. This should be handled in a dedicated function or a useEffect.

**Comment by daomcgill** [comment]
- Design-03: Remove commented out code
- Design-04: Add some descriptive comments
- React-01: Components could be broken down to simplify

**Comment by Ssunoo2** [comment]
L154,141: Duplicated code
L143, 156: Duplicated code
Could create helper functions for these

L189: delete commented out code
Could extract larger sections into smaller components for readability

**Comment by ehsuGit** [comment]
Architecture OK
Design 01 - I think the handleDelete function is also in the financial profile itself
Design 03 - Delete commented code line 189-191, fix comments on 214 and 234
JS and ESLint OK  
React OK
