### ISSUE TITLE
Review Issue 5:  InviteUsersByEmail

### ISSUE THREAD

**Issue by ehsuGit** [ICS-414-In5PIRE/in5PIRE-code#131]
Please review the [InviteUsersByEmail](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/components/Financial%20Profiles/InviteUsers.jsx)

Use these guidelines:
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

DUE: 10/14

**Comment by skulibas** [comment]
* REACT-04: You could destructure profileId directly in the function parameter for better readability.

**Comment by daomcgill** [comment]
- Consider checking for email format in input

**Comment by Ssunoo2** [comment]
L041: extracting form logic into helper functions could help flatten code

**Comment by ehsuGit** [comment]
InviteUsersByEmail
Architecture OK
Design OK
JS and ESLint OK
React OK
