### ISSUE TITLE
Review Issue 6: BudgetForm

### ISSUE THREAD

**Issue by ehsuGit** [ICS-414-In5PIRE/in5PIRE-code#143]
Please review the BudgetForm, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/BudgetForm.jsx)

Use these guidelines:
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

DUE: 10/21

**Comment by daomcgill** [comment]
Design-01: Could use an array for the form input pieces
Design-04: Add a description
For later: totalRevenue could be calculated in the component

**Comment by skulibas** [comment]
* Design-03: The empty callback in this.setState inside the handleChange() function is dead code.
* Design-08: The lines where data is fetched for budgetFormData are repeated multiple times.
* JS-05: The class methods componentDidMount, componentDidUpdate, and componentWillUnmount could be refactored into arrow functions.

**Comment by daomcgill** [comment]
React-07: Data should not be fetched inside of render, use useTracker to fetch the data. The state can then be used in render().
JS-05: Arrow functions could be used to simplify throughout.

**Comment by Ssunoo2** [comment]
BudgetForm:
There is some repeated logic in handlesubmit and handledelete that could be refactored into helper functions but I don’t think it’s really necessary as is.

**Comment by bfd2** [comment]
Some of the functions could use arrow functions for simplicity.

**Comment by ehsuGit** [comment]
Architecture OK
Design 02 - Might help to clean up the conditional block starting line 99
JS and ESLint OK
REACT OK

**Comment by lukepag** [comment]
JS-05: Use arrow functions more consistently throughout the page
REACT-07: Data is fetched in the render code
