### ISSUE TITLE
Review Issue 6: Revenue component

### ISSUE THREAD

**Issue by ehsuGit** [ICS-414-In5PIRE/in5PIRE-code#144]
Please review the Revenue Component, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/components/BudgetFormComponents/Revenue.jsx)

Use these guidelines:
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

DUE: 10/21

**Comment by daomcgill** [comment]
Design-01: Could use an array for the form input pieces
Design-04: Add a description
For later: totalRevenue could be calculated in the component

**Comment by skulibas** [comment]
Looks good

**Comment by Ssunoo2** [comment]
Revenue component: 
Design-01: There is some duplication with the form input, which could be refactored: 
Design-08: it’s pretty DRY but we could extract repeated code into helper functions

**Comment by bfd2** [comment]
Design: More comments needed to describe the code

**Comment by ehsuGit** [comment]
Architecture OK
Design 05 - could have more comments around
JS and ESLint OK  
React OK

**Comment by lukepag** [comment]
DESIGN-05: Include more comments
