### ISSUE TITLE
Review Issue 7: ProfileBudgetOverview

### ISSUE THREAD

**Issue by bfd2** [ICS-414-In5PIRE/in5PIRE-code#159]
Review [ProfileBudgetOverview](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/ProfileBudgetFormOverview.jsx)
Use these guidelines:

[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
[React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)
DUE: 10/28

**Comment by Ssunoo2** [comment]
Could calculate the years only once instead of each render
Add more comments to explain its functionality
The filenames and imported component names don’t match

**Comment by daomcgill** [comment]
If you use state variables for the years, it only has to calculate when updated
Could use more comments
Could use some validation, such as profileId and data existence

**Comment by skulibas** [comment]
* REACT-04:
    * useParams() is used but profileId is destructured in the body of the component instead of directly in the parameter list of the function

**Comment by bfd2** [comment]
More comments would be nice and calculating each year once would be more better instead of doing it on each render

**Comment by ehsuGit** [comment]
ProfileBudgetOverview
Architecture OK
Design OK
JS and ESLint OK
React OK

I think everything is okay, comments are good too.

**Comment by bobbyir** [comment]
ProfileBudgetOverview
Architecture OK
Design OK
JS and ESLint OK
React OK
