### ISSUE TITLE
Review Issue 7: Upload File

### ISSUE THREAD

**Issue by bfd2** [ICS-414-In5PIRE/in5PIRE-code#160]
[Upload File](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/UploadFile.jsx)
Use these guidelines:

[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
[React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)
DUE: 10/28

**Comment by Ssunoo2** [comment]
Comments should also clarify the purpose, not just ‘how’
Could separate some functions into reusable components for utility and readability

**Comment by daomcgill** [comment]
- It might be a little unclear to the user how you should go about updating data after it has been uploaded with the spreadsheet.
- Parsing could be a function.
- Images could benefits from have alts.

**Comment by skulibas** [comment]
- Extra space on line 12

**Comment by bfd2** [comment]
Condense both code and comments for readability

**Comment by ehsuGit** [comment]
Upload File
Architecture OK
Design 05 - remove the todo comments once done, some comments are also unnecessary
JS and ESLint OK
React OK

**Comment by bobbyir** [comment]
ProfileBudgetOverview
Architecture OK
Design OK
JS and ESLint OK
React OK

**Comment by lukepag** [comment]
Everything looks good
