### ISSUE TITLE
Review Issue 8: BudgetFormInputCollection

### ISSUE THREAD

**Issue by ehsuGit** [ICS-414-In5PIRE/in5PIRE-code#176]
Please review BudgetFormInputCollection.js, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/api/BudgetFormInput/BudgetFormInputCollection.js)

Use these guidelines:

[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
[React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)
DUE: 11/4

**Comment by skulibas** [comment]
- Design-01 & Design-08: The calculations in the define and update methods contain repeated blocks for calculating totals like totalRevenue, totalExpenses, and fringeBenefits.
    - JS-03: In the update function, constructing updatedDataWithCalculations could benefit from using the spread operator to simplify merging properties.

**Comment by daomcgill** [comment]
- Design-01: Duplication in define and update could be avoided by using a method to calculate the fields.

**Comment by Ssunoo2** [comment]
* There are duplicated functions for totalRevenue, totalExpense, and fringeBenefits in the update.
* The budget fields are also duplicated many times. They could potentially be defined as an array

**Comment by bobbyir** [comment]
Design-01 (Refactor to Reduce Duplication): The code has repetitive calculations, Consider abstracting these calculations into helper functions.

**Comment by bfd2** [comment]
Duplicate functions could be considered into a single function

**Comment by ehsuGit** [comment]
Architecture OK
Design 01/08 - The huge blocks of input data could be stored somewhere else, duplicated 4 
times in the code
09 - Duplicated code could be moved somewhere else for reuse
JS and ESLint OK
React OK
