### ISSUE TITLE
Review Issue 8: Dashboard.jsx

### ISSUE THREAD

**Issue by ehsuGit** [ICS-414-In5PIRE/in5PIRE-code#177]
Please review Dashboard.jsx, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/Dashboard.jsx)

Use these guidelines:

[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
[React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)
DUE: 11/4

**Comment by Ssunoo2** [comment]
Could make functions to consolidate the code for the charts
They could also be separate components

**Comment by bobbyir** [comment]
Design-01: The repeated chart configuration structures for different time frames (4, 8, and 12 years) can be streamlined. Creating a utility function that generates these configurations based on a specified year would make the code cleaner.

**Comment by bfd2** [comment]
Chart configurations could be considering into a single function or other components as well

**Comment by ehsuGit** [comment]
Architecture OK
Design -- 01 - Still looks repetitive w/ the years and charts. is there is a way to separate data processing and the rendering? this still works fine though
JS and ESLint -- 08 - some comments on the file and what it does
React OK
