### ISSUE TITLE
Review Issue 9: Charts

### ISSUE THREAD

**Issue by ehsuGit** [ICS-414-In5PIRE/in5PIRE-code#186]
Please review Charts.jsx, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/components/DashboardComponents/Charts.jsx)

Use these guidelines:

[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
[React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)
DUE: 11/11

**Comment by Ssunoo2** [comment]
* Could add more jsdoc comments explaining functionality
* Repeated logic in setDataChartConfigs

**Comment by daomcgill** [comment]
- Chart configuration duplicated multiple times, should probably be a function

**Comment by bobbyir** [comment]
Define the query as a constant for better readability.

**Comment by ehsuGit** [comment]
Architecture OK
Design 01/08 - setChartDataConfigs feels repetitive
JS and ESLint OK
React OK

**Comment by bfd2** [comment]
setChartDataConfigs could be simplified into one function

**Comment by skulibas** [comment]
As been mentioned multiple times above, setChartDataConfigs is repetitive. Other than that, it looks good.

**Comment by lukepag** [comment]
Everything looks good

**Comment by lukepag** [comment]
Summary

- Fix repetitive nature of setChartDataConfigs
- Add more comments
- Define query as a constant
