### ISSUE TITLE
Review Issue 9: profiledashboard

### ISSUE THREAD

**Issue by ehsuGit** [ICS-414-In5PIRE/in5PIRE-code#187]
Please review profiledashboard, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/ProfileDashboard.jsx)

Use these guidelines:

[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
[React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)
DUE: 11/11

**Comment by bobbyir** [comment]
You can simplify code by combining the similar navigation functions into a single function to reduce repetition.

**Comment by ehsuGit** [comment]
Architecture OK
Design 01 - active tabs repeated 
JS and ESLint OK
React - lots of handlers, could move somewhere else? Whole file could be broken up into smaller parts

**Comment by bfd2** [comment]
More simplification and more comments are needed as this feels very convoluted to look at.

**Comment by lukepag** [comment]
Feels like this could be spread out into more components

**Comment by lukepag** [comment]
Summary:
- Readability should be worked on
- Use more separate components
- Nested conditional
- Add more comments to explain code
