### ISSUE TITLE
Review Issue 10: Methods.js

### ISSUE THREAD

**Issue by ehsuGit** [ICS-414-In5PIRE/in5PIRE-code#205]
Please review Methods.js, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/ac989dc4dcf6ab534e8eb89ab85bd09a3cc4ad7c/app/imports/startup/both/Methods.js)

Use these guidelines:

[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
[React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)
DUE: 11/18

**Comment by skulibas** [comment]
- Design-05: Lines 11, 12, 14 should be removed if commented out

**Comment by Ssunoo2** [comment]
* updateHistoricalData could dynamically find 'year's instead of hard coding it. 
* Commented out code should be removed
*

**Comment by bobbyir** [comment]
Storing verification code in memory can be unreliable

**Comment by lukepag** [comment]
Delete unused imports

**Comment by ehsuGit** [comment]
Architecture OK
Design 03 - If the imports in the beginning are not used, delete them 
- are there more years that will be available in the historical data aside from 2020-24?
JS and ESLint OK
React OK

**Comment by bfd2** [comment]
Remove commented code
