### ISSUE TITLE
Review Issue 11: BalanceSheetInput.jsx

### ISSUE THREAD

**Issue by bfd2** [ICS-414-In5PIRE/in5PIRE-code#215]
Review file BalanceSheetInput.jsx [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/8425137981c3423842b5cd629bd065ba185592f3/app/imports/ui/pages/BalanceSheetInput.jsx).

Use these guidelines:

[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
[React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)
DUE: 11/25

**Comment by Ssunoo2** [comment]
line 38 have commented out code that should be deleted
Helper functions could be made into utility files
console.log on line 69 should be removed

**Comment by bfd2** [comment]
Remove L38 commented code, remove console.log from L69, some functions could either be condensed or made into files to be used elsewhere.

**Comment by bobbyir** [comment]
TDesign01: he snackbar handling logic is repetitive throughout the component. Each time you want to show a snackbar message, you call this.handleSnackBar with specific arguments. This leads to unnecessary duplication.

**Comment by ehsuGit** [comment]
BalanceSheetInput
Architecture OK
Design 03 - some commented out code on line 38, is this being used?
JS and ESLint 07 - remove console log on line 67
React OK
