### ISSUE TITLE
Review Issue 11: InvestmentPercentagesTable.jsx

### ISSUE THREAD

**Issue by bfd2** [ICS-414-In5PIRE/in5PIRE-code#216]
Review file InvestmentPercentagesTable.jsx [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/f0450fbad1469a2773c746e1b1cab73f79b1fc8c/app/imports/ui/components/Investment/InvestmentPercentagesTable.jsx).
relating to workpaper 2005-02
Use these guidelines:

[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
[React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)
DUE: 11/25

**Comment by daomcgill** [comment]
- Design-03: Line 38 is commented out, and can be removed.
- React-01: Form could be a separate component.

**Comment by Ssunoo2** [comment]
* Make sure subscription unmounts
* Add loading if table isn't loaded in yet

**Comment by daomcgill** [comment]
Design-01: rows has repeating code. A helper function would be useful.

**Comment by skulibas** [comment]
Design 01: The structure for rows has repetitive keys and calculations. This can be refactored into a reusable function or mapping logic to generate rows dynamically, reducing redundancy. Similarly, the summary object could benefit from programmatically generating its properties to improve readability and reduce duplication.

**Comment by bfd2** [comment]
Rows could be condensed into a helper function for better readability and less repetition.

**Comment by bobbyir** [comment]
No null or undefined checks for fields in investmentData.

**Comment by ehsuGit** [comment]
InvestmentPercentagesTable
Architecture OK
Design 01 - repetitive code, file will be much shorter and concise after refactoring
JS and ESLint OK
React OK
