### ISSUE TITLE
Review: Landing Page

### ISSUE THREAD

**Issue by Ssunoo2** [ICS-414-In5PIRE/in5PIRE-code#59]
Please review the landing page, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/Landing.jsx)

Use these guidelines:
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

**Comment by skulibas** [comment]
Nothing is wrong with the code, but should probably stay consistent on with JS framework to use. Currently were using bootstrap for this and semantics ui for the balance sheet page.

**Comment by Ssunoo2** [comment]
L06: Could change to multiple lines for readability
<section 
id="landing-page" 
className="land-img min-vh-100 min-vw-100 d-flex align-items-center text-center text-white container-fluid">

Everything else looks fine and seems to pass the checklists

**Comment by bfd2** [comment]
Landing.jsx

Line 3: Change the default comment from the template.

Line 7: Delete extra space in container className

Lines 15-16: Ending space needed at the end of /a
<a href="/about" className="btn btn-light ms-3"> About us </a>

Put the href after className so that it's easier to cross reference where it goes.
`<a className="btn btn-light ms-3" href="/about"> About us </a>`

**Comment by skulibas** [comment]
Nothing is wrong with the code, but should probably stay consistent with the JS framework to use. Currently we are using bootstrap for this and semantics ui for the balance sheet page.

**Comment by ehsuGit** [comment]
Landing.jsx
Architecture OK
Design OK
JS and ESlint OK
React OK

**Comment by daomcgill** [comment]
Cannot find issues with this file.

**Comment by lukepag** [comment]
I feel everything in the code is simple and easy to read

**Comment by Ssunoo2** [comment]
## Outcome of the review meeting

**Comment by Ssunoo2** [comment]
## Outcome of the review meeting
### New Issues
None

### Checklists
None

The code is simple enough and not showing any errors

**Comment by bobbyir** [comment]
No issues found
