### ISSUE TITLE
Review: BalanceSheetInput

### ISSUE THREAD

**Issue by Ssunoo2** [ICS-414-In5PIRE/in5PIRE-code#60]
Please review the Balanace input page, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/BalanceSheetInput.jsx)

Use these guidelines:
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

**Comment by skulibas** [comment]
- formData is quite long; would be better to put it into its own file
- Might be better to switch to a class component instead of functional since there are states in this component
- Get rid of console log on line 54

**Comment by Ssunoo2** [comment]
L63-71, L79-81: “Form successfully submitted” code duplicated twice - can make into its own function. 
L85-106: Menu.Item elements are all repeated for each element

**Comment by skulibas** [comment]
formData is quite long; would be better to put it into its own file
Might be better to switch to a class component instead of functional since there are states in this component
Get rid of console log on line 54

**Comment by bfd2** [comment]
Line 54: Get rid of console.log [JS-07](https://github.com/cammoore/campus-cravings/blob/main/checklists/js-checklist.md#js-07-avoid-consolelogs)

Otherwise lgtm.

**Comment by daomcgill** [comment]
Design01: duplicate success message for form submitted
Maybe use async and await for handleSubmit?

**Comment by ehsuGit** [comment]
## Outcome of the review meeting
### New Issues
Make function that maps over menu items instead of repeating code

### Checklists
Make function for form submitted
Remove the console.log() on line 54

**Comment by lukepag** [comment]
The error catch is in the return statement, this could be changed to its own function

**Comment by bobbyir** [comment]
You can deconstruct form data into form components to avoid repeated formData.property
