### ISSUE TITLE
Add an editFinancialProfile page

### ISSUE THREAD

**Issue by Ssunoo2** [ICS-414-In5PIRE/in5PIRE-code#61]
Should be able to edit the financial profile as well as the input data

**Comment by daomcgill** [comment]
I ended up doing this when I was trying to link the Edit Profile. Sorry about that!

**Comment by ehsuGit** [comment]
> I ended up doing this when I was trying to link the Edit Profile. Sorry about that!

It's okay! Thank you for doing it, I couldn't figure it out at all.
