### ISSUE TITLE
Review2: AboutUs

### ISSUE THREAD

**Issue by Ssunoo2** [ICS-414-In5PIRE/in5PIRE-code#77]
Please review the About use page, linked [here](https://github.com/ICS-414-In5PIRE/in5PIRE-code/blob/main/app/imports/ui/pages/AboutUs.jsx)

Use these guidelines:
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

**Comment by skulibas** [comment]
Might want to update our members
Extra line on line 74, 76

**Comment by bobbyir** [comment]
REACT-01: Components should be simple

The team member cards should be put into a subcomponent to keep the component smaller and more readable.

**Comment by bfd2** [comment]
Remove console.log from L48

**Comment by daomcgill** [comment]
Since the first row of members is in alphabetical order, consider making the second row the same.
Use a component or a map function for the team members.

**Comment by Ssunoo2** [comment]
Aboutus
L08: redundant container inside React-bootstrap container
L12: could use <article> or <section> instead of h1
L34-73: could define the team members in an array and map over it instead of hard coding each one

**Comment by lukepag** [comment]
Using a component for the team members would make managing them a lot easier if we decided to add more information as well as making it more readable

**Comment by ehsuGit** [comment]
Architecture OK
Design OK
JS and ESLint OK
React OK

**Comment by Ssunoo2** [comment]
## Outcome of review Meeting

### New issues
Make component for team members

### New checklist items
remove redundant container on L07
